server:
  port: 8081

spring:
  application:
    name: card-service
  profiles:
    active:
          - dev

# eureka client-server configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

# actuator /info endpoint
info:
  app:
    name: card-service
    description: This is card service to maintain the card for virtusa assignment
    version: 1.0.0


